# Generated by Django 4.0.4 on 2022-07-02 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_producto_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(max_length=30)),
                ('fecha', models.CharField(max_length=30)),
                ('Producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producto')),
            ],
        ),
    ]
